version: '2.2'

services:
  tep:
    container_name: tep
    environment:
      - NODE_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./:/code
      - /code/node_modules
    command: "npm run dev"
    networks:
      - tep

  postgres12:
    hostname: postgres12
    container_name: postgres12
    build:
      context: ./postgres
      dockerfile: Dockerfile12
    environment:
      - POSTGRES_USER=postgres12
      - POSTGRES_DB=postgres12
      - POSTGRES_PASSWORD=postgres12
    ports:
       - 5432:5432
    networks:
      - tep

  postgres14:
    hostname: postgres14
    container_name: postgres14
    build:
      context: ./postgres
      dockerfile: Dockerfile14
    environment:
      - POSTGRES_USER=postgres14
      - POSTGRES_DB=postgres14
      - POSTGRES_PASSWORD=postgres14
    ports:
       - 5432:5431
    networks:
      - tep

networks:
  tep:
    driver: bridge

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
